name = "aviation-expeditions"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts", "src/**/*.tsx", "app/**/*.ts", "app/**/*.tsx"]

[build.upload]
format = "service-worker"

[env.production]
vars = { ENVIRONMENT = "production" }

[site]
bucket = "out"
